# This file is part of the Apathetic Guide to IdleOn project.
#
# Apathetic Tools Â© 2025 (https://github.com/apathetic-tools)
#
# This source code is dual-licensed:
#  - Under the GNU Affero General Public License v3.0 (AGPLv3).
#  - Under alternative licensing terms by the copyright holder.
#
# See CODE-LICENSE for details.
#
# SPDX-License-Identifier: AGPL-3.0-or-later

blank_issues_enabled: false
contact_links:
  - name: ğŸ’ Community
    url: https://discord.gg/PW6GahZ7
